services:

  network_service:
    networks:
      - eazybytes_network

  network_deploy_service:
    extends:
      service: network_service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: rabbit_mq_service

  network_deploy_env_service:
    extends:
      service: network_deploy_service
    environment:
      SPRING_PROFILES_ACTIVE: "qa"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server-container:8071/"
